import fs from "node:fs";
import path from "node:path";

export type PackageManager = "pnpm" | "yarn" | "npm" | "bun";

export interface InitConfig {
  host: string;
  port: number;
  output: string;
}

export interface InitFile {
  path: string;
  contents: string;
}

export interface InitPlan {
  config: InitConfig;
  configPath: string;
  files: InitFile[];
  dependencies: string[];
  installCommand: string;
  gitignoreEntry: string;
  nextSteps: string[];
  hasExpress: boolean;
  telemetryDetected: boolean;
  telemetrySignals: TelemetrySignal[];
}

export interface PackageJsonLike {
  dependencies?: Record<string, string>;
  devDependencies?: Record<string, string>;
}

export interface BuildInitPlanInput {
  cwd: string;
  pkg: PackageJsonLike;
  packageManager: PackageManager;
  port?: number;
  env?: Record<string, string | undefined>;
}

export type TelemetrySignal =
  | "opentelemetry"
  | "sentry"
  | "datadog"
  | "otlp-env"
  | "collector-config"
  | "splunk";

export interface TelemetryDetection {
  detected: boolean;
  signals: TelemetrySignal[];
}

const COLLECTOR_CONFIG_FILES = [
  "otel-collector-config.yaml",
  "otel-collector-config.yml",
  "otelcol.yaml",
  "otelcol.yml",
  "otel-collector.yaml",
  "otel-collector.yml",
];

// Splunk-specific collector/agent config filenames (kept separate from the otel list).
const SPLUNK_CONFIG_FILES = [
  "splunk-otel-collector.yaml",
  "splunk-otel-collector.yml",
  "agent_config.yaml",
  "agent_config.yml",
];

const SPLUNK_ENV_VARS = [
  "SPLUNK_ACCESS_TOKEN",
  "SPLUNK_REALM",
  "SPLUNK_HEC_TOKEN",
];

function isSplunkDep(name: string): boolean {
  return (
    name.startsWith("@splunk/") ||
    name === "splunk-otel-js" ||
    name === "splunk-logging"
  );
}

/** Pure detection of existing telemetry. Reads only the inputs given (no process.env). */
export function detectTelemetry(input: {
  cwd: string;
  pkg: PackageJsonLike;
  env?: Record<string, string | undefined>;
}): TelemetryDetection {
  const env = input.env ?? {};
  const deps = {
    ...(input.pkg.dependencies ?? {}),
    ...(input.pkg.devDependencies ?? {}),
  };
  const names = Object.keys(deps);
  const signals: TelemetrySignal[] = [];
  if (names.some((n) => n.startsWith("@opentelemetry/")))
    signals.push("opentelemetry");
  if (names.some((n) => n.startsWith("@sentry/"))) signals.push("sentry");
  if (deps["dd-trace"]) signals.push("datadog");
  if (env.OTEL_EXPORTER_OTLP_ENDPOINT) signals.push("otlp-env");
  if (
    COLLECTOR_CONFIG_FILES.some((f) => fs.existsSync(path.join(input.cwd, f)))
  )
    signals.push("collector-config");
  const splunkDep = names.some(isSplunkDep);
  const splunkEnv = SPLUNK_ENV_VARS.some((k) => env[k]);
  const splunkConfig = SPLUNK_CONFIG_FILES.some((f) =>
    fs.existsSync(path.join(input.cwd, f)),
  );
  if (splunkDep || splunkEnv || splunkConfig) signals.push("splunk");
  return { detected: signals.length > 0, signals };
}

const DEPENDENCIES = ["crumbtrail-core", "crumbtrail-node"];
const DEFAULT_PORT = 9898;
const DEFAULT_HOST = "127.0.0.1";

/** Detect the package manager from lockfiles, defaulting to npm. */
export function detectPackageManager(cwd: string): PackageManager {
  if (fs.existsSync(path.join(cwd, "pnpm-lock.yaml"))) return "pnpm";
  if (fs.existsSync(path.join(cwd, "yarn.lock"))) return "yarn";
  if (fs.existsSync(path.join(cwd, "bun.lockb"))) return "bun";
  return "npm";
}

function installCommandFor(pm: PackageManager, deps: string[]): string {
  const list = deps.join(" ");
  switch (pm) {
    case "npm":
      return `npm install ${list}`;
    case "yarn":
      return `yarn add ${list}`;
    case "bun":
      return `bun add ${list}`;
    case "pnpm":
    default:
      return `pnpm add ${list}`;
  }
}

function hasDependency(pkg: PackageJsonLike, name: string): boolean {
  return Boolean(pkg.dependencies?.[name] ?? pkg.devDependencies?.[name]);
}

function clientHelper(endpoint: string): string {
  return `// Generated by \`crumbtrail-server init\`. Import this once at your app's browser entry point.
//
// IMPORTANT: the specifier below must stay a LITERAL string. Vite's dev server can only
// pre-bundle bare imports it sees statically; a computed dynamic specifier reaches the
// browser unresolved and capture silently no-ops. \`crumbtrail-server doctor\` checks this file.
export const crumbtrailReady = import('crumbtrail-core').then(({ Crumbtrail }) =>
  Crumbtrail.init({
    httpEndpoint: '${endpoint}',
  }),
);
`;
}

function serverHelper(endpoint: string): string {
  return `// Generated by \`crumbtrail-server init\`. Wire these into your Express app.
const {
  createCrumbtrailExpressMiddleware,
  createCrumbtrailExpressErrorMiddleware,
} = require('crumbtrail-node');

const ENDPOINT = '${endpoint}';

// Call attachCrumbtrail(app) BEFORE your routes.
function attachCrumbtrail(app) {
  app.use(createCrumbtrailExpressMiddleware({ endpoint: ENDPOINT }));
}

// Add this AFTER your routes so backend errors are correlated to the request.
const crumbtrailErrorMiddleware = createCrumbtrailExpressErrorMiddleware({ endpoint: ENDPOINT });

module.exports = { attachCrumbtrail, crumbtrailErrorMiddleware };
`;
}

function telemetryRecipe(endpoint: string, signals: TelemetrySignal[]): string {
  return `# Plug your existing telemetry into Crumbtrail

\`crumbtrail-server init\` detected existing telemetry in this project: ${signals.join(", ") || "none"}.

Instead of installing a second backend SDK, point your existing exporter at Crumbtrail's
OTLP receiver. Crumbtrail ingests standard OTLP/HTTP-JSON and maps it into its AI-readable,
ranked bug bundle — so you reuse the instrumentation you already have.

## 1. Send OTLP to Crumbtrail

- Traces:  POST ${endpoint}/v1/traces
- Logs:    POST ${endpoint}/v1/logs

Add Crumbtrail as an *additional* exporter (keep your current one). For an OpenTelemetry
SDK, set or add the endpoint:

    OTEL_EXPORTER_OTLP_ENDPOINT=${endpoint}
    OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf   # or http/json

For full per-vendor recipes (OTel Collector, Sentry, Datadog, Grafana Alloy, Honeycomb,
Splunk) see the Crumbtrail docs/integrations/ directory.

## 2. Join traces to a session

Set the resource attribute \`crumbtrail.session.id\` to the session id your frontend
started. Crumbtrail uses it to file backend spans/logs into the same session as the
frontend, and correlates the two by W3C \`traceparent\` (trace id).

## 3. Keep the frontend on the Crumbtrail SDK

Your browser entry point still imports \`./crumbtrail.client.js\` — frontend interaction
capture is Crumbtrail's differentiator and is not replaced by OTel.
`;
}

/** Build a deterministic, side-effect-free plan for `crumbtrail-server init`. */
export function buildInitPlan(input: BuildInitPlanInput): InitPlan {
  const { cwd, pkg, packageManager } = input;
  const port = input.port ?? DEFAULT_PORT;
  const endpoint = `http://${DEFAULT_HOST}:${port}`;
  const hasExpress = hasDependency(pkg, "express");
  const telemetry = detectTelemetry({ cwd, pkg, env: input.env });

  const files: InitFile[] = [
    {
      path: path.join(cwd, "crumbtrail.client.js"),
      contents: clientHelper(endpoint),
    },
  ];
  const nextSteps: string[] = [
    `Import './crumbtrail.client.js' once at your app's browser entry point.`,
  ];

  if (telemetry.detected) {
    files.push({
      path: path.join(cwd, "crumbtrail.telemetry.md"),
      contents: telemetryRecipe(endpoint, telemetry.signals),
    });
    nextSteps.push(
      `Existing telemetry detected (${telemetry.signals.join(", ")}). Point your exporter at ${endpoint}/v1/traces and ${endpoint}/v1/logs.`,
      `Add the resource attribute crumbtrail.session.id to join traces to a session — see ./crumbtrail.telemetry.md.`,
    );
  } else if (hasExpress) {
    files.push({
      path: path.join(cwd, "crumbtrail.server.js"),
      contents: serverHelper(endpoint),
    });
    nextSteps.push(
      `In your Express app: const { attachCrumbtrail, crumbtrailErrorMiddleware } = require('./crumbtrail.server.js');`,
      `Call attachCrumbtrail(app) before your routes, and app.use(crumbtrailErrorMiddleware) after them.`,
    );
  }

  nextSteps.push(
    `Start the server:  crumbtrail-server serve`,
    `Verify the wiring: crumbtrail-server doctor`,
  );

  return {
    config: {
      host: DEFAULT_HOST,
      port,
      output: path.join(cwd, ".crumbtrail", "sessions"),
    },
    configPath: path.join(cwd, "crumbtrail.config.json"),
    files,
    dependencies: [...DEPENDENCIES],
    installCommand: installCommandFor(packageManager, DEPENDENCIES),
    gitignoreEntry: ".crumbtrail/",
    nextSteps,
    hasExpress,
    telemetryDetected: telemetry.detected,
    telemetrySignals: telemetry.signals,
  };
}
